檔案網址
https://www.superdatascience.com/machine-learning/

In [39]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt #pyplot是次libraries
from os import listdir
from os.path import isfile,isdir,join
from os import walk


In [12]:
mypath = "Machine Learning A-Z Template Folder/Part 1 - Data Preprocessing/Section 2 -------------------- Part 1 - Data Preprocessing --------------------/Data_Preprocessing"
files = listdir(mypath)

# 遞迴列出所有子目錄與檔案
for root, dirs, files in walk(mypath):#找出資料夾內容
  print("路徑：", root)
  print("  目錄：", dirs)
  print("  檔案：", files)

for root, dirs, files in walk(mypath): #讀取絕對路徑
  for f in files:
    fullpath = join(root, f)
    print(fullpath)

路徑： Machine Learning A-Z Template Folder/Part 1 - Data Preprocessing/Section 2 -------------------- Part 1 - Data Preprocessing --------------------/Data_Preprocessing
  目錄： []
  檔案： ['.DS_Store', 'categorical_data.py', 'categorical_data.R', 'Data.csv', 'data_preprocessing_template.py', 'data_preprocessing_template.R', 'missing_data.py', 'missing_data.R']
Machine Learning A-Z Template Folder/Part 1 - Data Preprocessing/Section 2 -------------------- Part 1 - Data Preprocessing --------------------/Data_Preprocessing/.DS_Store
Machine Learning A-Z Template Folder/Part 1 - Data Preprocessing/Section 2 -------------------- Part 1 - Data Preprocessing --------------------/Data_Preprocessing/categorical_data.py
Machine Learning A-Z Template Folder/Part 1 - Data Preprocessing/Section 2 -------------------- Part 1 - Data Preprocessing --------------------/Data_Preprocessing/categorical_data.R
Machine Learning A-Z Template Folder/Part 1 - Data Preprocessing/Section 2 -------------------- Part 

In [37]:
datapath= mypath + '/'+ 'Data.csv' #可列出資料位置
testdata = pd.read_csv(datapath)

In [38]:
testdata

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [106]:
x = testdata.iloc[:,:-1].values #左邊的 : 是整行line（0-9）,右邊的:-1是列columns
y = testdata.iloc[:, 3].values
X = testdata.iloc[:,:-1].values

In [51]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'], dtype=object)

處理missing data 

In [52]:
from sklearn.preprocessing import Imputer

In [77]:
imputer = Imputer(missing_values = 'NaN',strategy = 'mean',axis = 0)
#NaN會變成中位數
#如果axis=0 impute along columns
#如果axis=1 impute along rows

In [112]:
imputer.fit(X[:,1:3])

Imputer(axis=0, copy=True, missing_values='NaN', strategy='mean', verbose=0)

In [114]:
X[:,1:3] = imputer.transform(X[:,1:3])

In [115]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [87]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [109]:
labelencoder_X = LabelEncoder() #分類，第一行有France、Spain、Germany，將其轉為0,1,2
X[:,0] = labelencoder_X.fit_transform(X[:,0])

In [110]:
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, nan],
       [0, 35.0, 58000.0],
       [2, nan, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [130]:
onehotencoder = OneHotEncoder(categorical_features = [0])
X = onehotencoder.fit_transform(X).toarray()
#Dummy encode
#france -->1,0,0
#Spain-->0,0,1
#Germany -->0,1,0
labelencoder_y = LabelEncoder() 
y = labelencoder_y.fit_transform(y)


In [131]:
y #將NO變為0 Yes 變為1

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [133]:
X

array([[  1.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          4.40000000e+01,   7.20000000e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          1.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          2.70000000e+01,   4.80000000e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          1.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          3.00000000e+01,   5.40000000e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          1.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          3.80000000e+01,   6.10000000e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          1.00

In [134]:
from sklearn.cross_validation import train_test_split

In [135]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state = 0,)
#要一次定義四個變數
#第一第二個變數是要放array
#test_size，如果0.2，就是20%是test,80%是training

In [141]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1])

feature scaling

In [142]:
from sklearn.preprocessing import StandardScaler

In [155]:
SC_X=StandardScaler()
X_train = SC_X.fit_transform(X_train) #問題-->需要scaling 前面的dummy encode嗎？
X_test = SC_X.transform(X_test)

In [156]:
X_train

array([[-1.        ,  1.        , -1.        ,  1.        , -1.        ,
         1.        , -1.        ,  2.64575131, -0.77459667,  0.26306757,
         0.12381479],
       [ 1.        , -1.        ,  1.        , -1.        ,  1.        ,
        -1.        ,  1.        , -0.37796447, -0.77459667, -0.25350148,
         0.46175632],
       [-1.        ,  1.        , -1.        ,  1.        , -1.        ,
         1.        , -1.        , -0.37796447,  1.29099445, -1.97539832,
        -1.53093341],
       [-1.        ,  1.        , -1.        ,  1.        , -1.        ,
         1.        , -1.        , -0.37796447,  1.29099445,  0.05261351,
        -1.11141978],
       [ 1.        , -1.        ,  1.        , -1.        ,  1.        ,
        -1.        ,  1.        , -0.37796447, -0.77459667,  1.64058505,
         1.7202972 ],
       [-1.        ,  1.        , -1.        ,  1.        , -1.        ,
         1.        , -1.        , -0.37796447,  1.29099445, -0.0813118 ,
        -0.167